version: "3"

services:
  master:
    container_name: master
    image: ghcr.io/dhzdhd/hadoop-docker-compose:v1.2.5
    ports:
      - 8088:8088
      - 9000:9000
      - 9870:9870
    volumes:
      - ./workdir:/workdir
