version: "3"

services:
  master:
    container_name: master
    build:
      context: .
      dockerfile: Dockerfile
      target: master
    ports:
      - 8088:8088
      - 9000:9000
      - 9870:9870
    volumes:
      - ./workdir:/workdir
      - ./config/hdfs:/home/hadoop/hdfs
